debug=true

# === LOGGING ===
logging.level.com.zoo.api=DEBUG
logging.level.root=INFO
logging.level.org.springframework=INFO

# === AFFICHAGE CONSOLE ===
spring.output.ansi.enabled=ALWAYS

# === INFOS APP ===
spring.application.name=zooApi
server.port=8081

# === JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# === BASE DE DONNÉES ===
spring.datasource.url=jdbc:mysql://mysql-kakti.alwaysdata.net:3306/kakti_zooapi?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === SÉCURITÉ DEV ===


# === DEVTOOLS ===
spring.devtools.restart.enabled=true
